export const boatData = [
  {
    id: 1,
    name: "Mafia Express",
    departure: "Mafia Island",
    arrival: "Mainland",
    departureTime: "08:00 AM",
    arrivalTime: "10:00 AM",
    date: "2024-03-25",
    price: 50,
    capacity: 100,
  },
  {
    id: 2,
    name: "Ocean Voyager",
    departure: "Mainland",
    arrival: "Mafia Island",
    departureTime: "11:00 AM",
    arrivalTime: "01:00 PM",
    date: "2024-03-25",
    price: 45,
    capacity: 80,
  },
  {
    id: 3,
    name: "Island Hopper",
    departure: "Mafia Island",
    arrival: "Mainland",
    departureTime: "02:00 PM",
    arrivalTime: "04:00 PM",
    date: "2024-03-25",
    price: 55,
    capacity: 120,
  },
  {
    id: 4,
    name: "Coastal Cruiser",
    departure: "Mainland",
    arrival: "Mafia Island",
    departureTime: "05:00 PM",
    arrivalTime: "07:00 PM",
    date: "2024-03-25",
    price: 50,
    capacity: 90,
  },
] 